# Generated by Django 3.2.12 on 2022-04-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, default='0', null=True)),
                ('bunk_name', models.CharField(max_length=100)),
                ('vehicle_type', models.BooleanField(default=False)),
                ('connector', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('phone', models.CharField(max_length=240, null=True)),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=240, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
