# Generated by Django 3.2.12 on 2022-04-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efuelapp', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bunk',
            old_name='owner_id',
            new_name='owner_ide',
        ),
        migrations.CreateModel(
            name='bunk_booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ide', models.IntegerField(blank=True, default='0', null=True)),
                ('name', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('phone', models.CharField(max_length=240, null=True)),
                ('uservehicle_type', models.BooleanField(default=False)),
                ('userconnector', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=240, null=True)),
                ('Bunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='efuelapp.bunk')),
            ],
        ),
    ]
