# Generated by Django 3.2.12 on 2022-04-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efuelapp', '0004_user_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='status',
            field=models.CharField(default='resign', max_length=240, null=True),
        ),
    ]
