# Generated by Django 3.2.12 on 2022-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efuelapp', '0005_alter_user_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='connector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bunk',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bunk_booked',
            name='userconnector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bunk_booked',
            name='uservehicle_type',
            field=models.CharField(max_length=100),
        ),
    ]
