# Generated by Django 3.2.12 on 2022-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efuelapp', '0007_bunk_booked_bunkowner_ide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk_booked',
            name='bunkowner_ide',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
