# Generated by Django 3.2.12 on 2022-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efuelapp', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='status',
            field=models.CharField(default='user', max_length=240, null=True),
        ),
    ]
