# Generated by Django 3.2.12 on 2022-05-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efuelapp', '0014_alter_user_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='owner_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=225)),
            ],
        ),
    ]
