# Generated by Django 3.2.12 on 2022-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efuelapp', '0016_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='items',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='price',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user_ide',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
